<?php
namespace vsk\modalForm;

use vsk\modalForm\assets\ModalFormAssets;
use yii\base\Exception;
use yii\base\Widget;

/**
 * Class ModalFormWidget
 * @package vsk\modalForm
 */
class ModalFormWidget extends Widget
{

    /**
     * @var string
     */
    public $url;

    /**
     * @var callable
     */
    public $template;

    /**
     * @return string|void
     */
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

        $view = $this->getView();
        ModalFormAssets::register($view);
        $view->registerJs('');
        if ($this->template instanceof \Closure) {
            $id = $this->getId();
            $modalId = $id.'-'.uniqid();
            $view->registerJs("$('#$id').vskModalForm('$modalId').init();");
            return call_user_func($this->template, $this);
        } else {
            throw new Exception('Set templdate for url');
        }
    }
}